project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "W. Jonas Reger"
  favicon: assets/images/masthead.png
  search:
    location: navbar
    type: overlay
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - pvalue-calculator.qmd

format:
  html:
    theme:
      # dark: darkly
      light: flatly
    css: styles.css
    toc: true

editor: visual
