project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "W. Jonas Reger"
  site-url: https://wjonasreger.github.io
  description: "Jonas Reger's professional website for data science"
  favicon: assets/images/masthead.png
  search:
    location: navbar
    type: overlay
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - pvalue-calculator.qmd
      - icon: github
        href: https://github.com/wjonasreger
      - icon: linkedin
        href: https://www.linkedin.com/in/wjonasreger/

format:
  html:
    theme:
      # dark: darkly
      light: flatly
    css: styles.css
    toc: true

editor: visual
